version: "3"

services:
  app:
    build: .
    command: yarn dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    depends_on:
      - db
    links:
      - db
  db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./.mongodb/data/db:/data/db
